# All about tensor

In [2]:
import torch
import numpy as np

## 1. Tensor 초기화

In [8]:
# 파이썬 배열로부터
data = [[1, 2], [3, 4]]

In [9]:
x_data = torch.tensor(data)

In [10]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# Numpy array로 부터
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [11]:
# 다른 텐서로 부터
x_ones = torch.ones_like(x_data) # x_data로 부터 가져온 속성을 유지함

In [12]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [17]:
x_rand = torch.rand_like(x_data, dtype = torch.float) # 특정 속성을 재정의하여 x_data의 속성을 덮어씀

In [18]:
x_rand

tensor([[0.3181, 0.5269],
        [0.2876, 0.9003]])

In [33]:
# Shape은 tensor의 차원을 나타내는 tuple로, 이를 이용하여 동일한 차원의 tensor 생성
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [34]:
rand_tensor

tensor([[0.2289, 0.6774, 0.6012],
        [0.2488, 0.6832, 0.0730]])

In [35]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [38]:
# Tensor의 속성
tensor = torch.rand(3,4)

print("Shape of tensor:{}".format(tensor.shape))
print("Datatype of tensor:{}".format(tensor.dtype))
print("Device tensor is stored on: {}".format(tensor.device))

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on: cpu


## 2.Tensor 연산

In [39]:
# GPU로 tensor 전송
tensor = tensor.to('cuda')

In [40]:
tensor.device

device(type='cuda', index=0)

In [61]:
tensor = torch.tensor([[i*4+j for j in range(4)] for i in range(4)] ,dtype=torch.int)

In [62]:
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int32)

In [70]:
# 첫행
tensor[0]

tensor([0, 1, 2, 3], dtype=torch.int32)

In [69]:
# 첫열
tensor[:,0]

tensor([ 0,  4,  8, 12], dtype=torch.int32)

In [71]:
# 마지막 열
tensor[:, -1]

tensor([ 3,  7, 11, 15], dtype=torch.int32)

In [72]:
# 텐서 결합
t1 = torch.cat([tensor, tensor, tensor], dim = 1)

In [73]:
t1

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]], dtype=torch.int32)

In [74]:
t1 = torch.cat([tensor, tensor, tensor], dim = 0)

In [75]:
t1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int32)

In [84]:
#산술연산
tensor = torch.tensor([[i for j in range(4)] for i in range(4)] ,dtype=torch.int)

In [85]:
tensor

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)

In [86]:
tensor.T

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]], dtype=torch.int32)

In [90]:
# 두 행렬 간 곱셈
y1 = tensor @ tensor.T

In [91]:
y1

tensor([[ 0,  0,  0,  0],
        [ 0,  4,  8, 12],
        [ 0,  8, 16, 24],
        [ 0, 12, 24, 36]], dtype=torch.int32)

In [92]:
y2 = tensor.matmul(tensor.T)

In [93]:
y2

tensor([[ 0,  0,  0,  0],
        [ 0,  4,  8, 12],
        [ 0,  8, 16, 24],
        [ 0, 12, 24, 36]], dtype=torch.int32)

In [94]:
# 요소별 곱셈을 계산
z1 = tensor * tensor

In [95]:
z1

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [4, 4, 4, 4],
        [9, 9, 9, 9]], dtype=torch.int32)

In [96]:
z2 = tensor.mul(tensor)

In [98]:
z2

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [4, 4, 4, 4],
        [9, 9, 9, 9]], dtype=torch.int32)

In [103]:
# aggregate 연산 
agg = tensor.sum()

In [104]:
agg

tensor(24)

In [105]:
# Scalar 값 변환
agg_scalar = agg.item()

In [106]:
agg_scalar

24

In [109]:
# Inplace 연산 => '_'를 접미사로 사용 (추후 모델 도함수 계산 시에 문제가 발생할 수 있으므로 권장하지 않음)
tensor.add_(5)

tensor([[10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12],
        [13, 13, 13, 13]], dtype=torch.int32)

## 3. Numpy 변환

In [110]:
t = torch.ones(5)

In [120]:
# Tensor to Numpy array
n = t.numpy()

In [121]:
n

array([3., 3., 3., 3., 3.], dtype=float32)

In [122]:
# Numpy and tensor CPU 메모리 공간 공유
t.add_(1)

tensor([4., 4., 4., 4., 4.])

In [123]:
t

tensor([4., 4., 4., 4., 4.])

In [124]:
n

array([4., 4., 4., 4., 4.], dtype=float32)

In [127]:
# Numpy to Tensor array

In [128]:
n = np.ones(5)

In [129]:
t = torch.from_numpy(n)

In [130]:
n

array([1., 1., 1., 1., 1.])

In [131]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)